Fix nectar not seeing redeem
coblox/nectar pull request #111
Opened 2020-08-25 05:13 UTC by D4nte

Resolves #108.

2020-08-25 05:24 UTC, thomaseizinger commented
Thank you for investigating and fixing this <3

2020-08-25 06:02 UTC, luckysori approved these changes
Nice! I think you missed one

2020-08-25 06:02 UTC, luckysori commented on src/network.rs
> +                            utc_start_of_swap: Utc::now().naive_local(),
:mega: I think it's
```suggestion
                            utc_start_of_swap: Utc::now().naive_utc(),
```

2020-08-25 06:03 UTC, luckysori requested changes
I meant to request changes oops

2020-08-26 02:27 UTC, D4nte commented on src/swap.rs
> +            utc_start_of_swap: chrono::Local::now().naive_local(),
And here!

2020-08-26 02:28 UTC, D4nte commented on src/swap/db.rs
> +            utc_start_of_swap: chrono::Local::now().naive_local(),
and here

2020-08-26 02:38 UTC, luckysori approved these changes

2020-08-26 23:40 UTC, D4nte commented
bors r+

2020-08-26 23:50 UTC, merged